/**
 * HAI3 Application Component
 *
 * Renders the Layout with AppRouter for screen navigation.
 * Layout components are generated by `hai3 scaffold layout` and owned by the project.
 *
 * HAI3Provider (in main.tsx) handles:
 * - Redux Provider setup
 * - HAI3 context (app instance)
 *
 * Layout handles:
 * - Header, Menu, Footer, Sidebar rendering
 * - Theme-aware styling via hooks
 *
 * AppRouter handles:
 * - Screen lazy loading
 * - Navigation state
 *
 * StudioOverlay (dev mode only):
 * - Development tools for theme/screenset switching
 * - Language selection
 * - API mode toggle (services register their own mocks)
 */

import { AppRouter } from '@hai3/react';
import { Layout } from '@/app/layout';
import { StudioOverlay } from '@hai3/studio';

function App() {
  return (
    <>
      <Layout>
        <AppRouter />
      </Layout>
      <StudioOverlay />
    </>
  );
}

export default App;
