/**
 * Header Component
 *
 * Application header with user info display.
 * Generated by `hai3 scaffold layout`.
 */

import React from 'react';
import { useAppSelector, type HeaderState } from '@hai3/react';
import { UserInfo } from '@hai3/uikit';

export interface HeaderProps {
  children?: React.ReactNode;
}

export const Header: React.FC<HeaderProps> = ({ children }) => {
  const headerState = useAppSelector((state) => state['layout/header'] as HeaderState | undefined);

  const user = headerState?.user;
  const loading = headerState?.loading ?? false;

  return (
    <header className="h-16 flex items-center px-4 border-b border-border bg-background">
      {children}
      <div className="ml-auto">
        <UserInfo
          displayName={user?.displayName}
          email={user?.email}
          avatarUrl={user?.avatarUrl}
          loading={loading}
        />
      </div>
    </header>
  );
};

Header.displayName = 'Header';
