/**
 * Layout Component
 *
 * Main layout orchestrator for the application.
 * This component is generated by `hai3 scaffold layout`.
 * Uses @hai3/uikit for UI components.
 */

import React, { useEffect } from 'react';
import { fetchCurrentUser } from '@/app/actions/bootstrapActions';
import { Footer } from './Footer';
import { Menu } from './Menu';
import { Sidebar } from './Sidebar';
import { Screen } from './Screen';
import { Popup } from './Popup';
import { Overlay } from './Overlay';
import { RoleSwitcher } from '@/screensets/insight/components/RoleSwitcher';

export interface LayoutProps {
  children?: React.ReactNode;
}

export const Layout: React.FC<LayoutProps> = ({ children }) => {
  useEffect(() => {
    // Bootstrap application on mount - fetch current user
    fetchCurrentUser();
  }, []);

  return (
    <div className="flex flex-col h-full w-full overflow-hidden">
      {/* Top row: Menu + Header + Content + Sidebar */}
      <div className="flex flex-1 overflow-hidden">
        {/* Menu - full height on left */}
        <Menu>
          <div className="mt-auto border-t border-gray-200 pt-1 pb-2">
            <RoleSwitcher />
          </div>
        </Menu>

        {/* Right side: Content */}
        <div className="flex flex-col flex-1 overflow-hidden">
          {/* Main content area */}
          <div className="flex flex-1 overflow-hidden">
            {/* Main content */}
            <Screen>{children}</Screen>

            {/* Sidebar */}
            <Sidebar />
          </div>
        </div>
      </div>

      {/* Footer - full width */}
      <Footer />

      {/* Popups */}
      <Popup />

      {/* Overlay */}
      <Overlay />
    </div>
  );
};

Layout.displayName = 'Layout';
