/**
 * insight API Mocks
 * Mock data for development and testing
 *
 * Keys use full URL patterns (including baseURL path).
 * Register mocks via MockPlugin in main.tsx or screenset.
 *
 * POST handlers serve raw backend data generated by factories.ts.
 * Legacy GET endpoints (dashboard, speed) are retained unchanged.
 *
 * ALL mock data comes from factory functions -- no fixture imports.
 */

import type { MockMap } from '@hai3/react';
import type {
  DashboardData,
  SpeedData,
  DrillData,
  DrillRow,
  TimeOffNotice,
  ODataParams,
  ODataResponse,
  TeamMember,
} from '../types';
import type {
  RawExecSummaryRow,
  RawTeamMemberRow,
  RawBulletAggregateRow,
  RawIcAggregateRow,
  RawLocTrendRow,
  RawDeliveryTrendRow,
} from './rawTypes';
import { METRIC_REGISTRY } from './metricRegistry';
import {
  mockExecRows,
  mockTeamMemberRows,
  mockTeamMemberRowsForTeam,
  mockTeamBulletSection,
  mockIcScenario,
  PEOPLE,
} from './mocks/factories';

// Re-export all factory functions for test / story consumers
export {
  mockExecRows,
  mockTeamMemberRows,
  mockIcAggregateRow,
  mockTeamBulletSection,
  mockIcBulletSection,
  mockLocTrendSeries,
  mockDeliveryTrendSeries,
  mockExecRow,
  mockTeamMemberRow,
  mockLocTrendRow,
  mockDeliveryTrendRow,
  mockBulletRow,
  mockExecScenario,
  mockTeamScenario,
  mockIcScenario,
} from './mocks/factories';

// ---------------------------------------------------------------------------
// Legacy inline mocks (small)
// ---------------------------------------------------------------------------

const mockDashboardData: DashboardData = {
  stats: [
    { key: 'total_commits', value: '4.2K', sub: '825.5K lines added' },
    { key: 'lines_of_code', value: '1.2M', sub: '+928.5K - 313.8K' },
    { key: 'ai_involvement', value: '86%', sub: 'ai_involvement_sub' },
    { key: 'active_total', value: '402 / 582', sub: 'active_total_sub' },
  ],
  chartData: [
    { date: '03-19', aiLoc: 170, commitLoc: 300 },
    { date: '03-20', aiLoc: 150, commitLoc: 155 },
    { date: '03-21', aiLoc: 155, commitLoc: 160 },
    { date: '03-22', aiLoc: 165, commitLoc: 200 },
    { date: '03-23', aiLoc: 280, commitLoc: 290 },
    { date: '03-24', aiLoc: 200, commitLoc: 270 },
    { date: '03-25', aiLoc: 150, commitLoc: 175 },
    { date: '03-26', aiLoc: 140, commitLoc: 160 },
    { date: '03-27', aiLoc: 130, commitLoc: 150 },
    { date: '03-28', aiLoc: 120, commitLoc: 140 },
    { date: '03-29', aiLoc: 110, commitLoc: 130 },
    { date: '03-30', aiLoc: 100, commitLoc: 120 },
    { date: '03-31', aiLoc: 130, commitLoc: 380 },
  ],
  bottomMetrics: [
    { key: 'avg_ai_suggested', value: '235' },
    { key: 'avg_ai_accepted', value: '261' },
    { key: 'avg_ai_deleted', value: '31' },
    { key: 'avg_ai_nloc', value: '261' },
    { key: 'avg_ai_loc', value: '273' },
    { key: 'avg_commit_added', value: '96' },
    { key: 'avg_commit_deleted', value: '22' },
    { key: 'avg_commit_nloc', value: '108' },
    { key: 'avg_commit_loc', value: '137' },
  ],
  periodSplits: [
    { label: '2026-03-19 \u2192 2026-03-25', value: 156 },
    { label: '2026-03-26 \u2192 2026-03-31', value: 123 },
  ],
  periodDelta: -33,
};

const mockSpeedData: SpeedData = {
  value: 42,
  min: 0,
  max: 70,
  unit: 'km/h',
  label: 'current_speed',
};

// ---------------------------------------------------------------------------
// Mock handler helpers
// ---------------------------------------------------------------------------

function odata(body: unknown): ODataParams {
  return (body ?? {}) as ODataParams;
}
function person(filter: string): string {
  return /person_id eq '([^']+)'/.exec(filter)?.[1] ?? 'p1';
}
function team(filter: string): string {
  return /org_unit_id eq '([^']+)'/.exec(filter)?.[1] ?? 'backend';
}
function wrap<T>(items: T[]): ODataResponse<T> {
  return { items, page_info: { has_next: false, cursor: null } };
}
function drillId(filter: string): string {
  return /drill_id eq '([^']+)'/.exec(filter)?.[1] ?? '';
}

/**
 * Deterministic seed derived from $filter string.
 * Different filter strings produce different (but stable) variation offsets,
 * so mock data varies per period/team/person but stays reproducible.
 */
function filterSeed(filter: string): number {
  let h = 0;
  for (let i = 0; i < filter.length; i++) {
    h = ((h << 5) - h + filter.charCodeAt(i)) | 0;
  }
  return Math.abs(h);
}

/** Deterministic pseudo-random variation based on index */
function vary(base: number, index: number, spread: number): number {
  const hash = Math.sin(index * 9301 + 49297) * 49297;
  const factor = (hash - Math.floor(hash)) * 2 - 1; // -1 to 1
  return Math.round((base + factor * spread) * 10) / 10;
}

/** Apply deterministic variation to a team member row */
function varyMember(r: RawTeamMemberRow, seed: number): Partial<RawTeamMemberRow> {
  if (seed === 0) return {};
  const factor = 0.85 + ((seed % 30) / 100);
  return {
    tasks_closed: Math.round(r.tasks_closed * factor),
    bugs_fixed: Math.round(r.bugs_fixed * factor),
    prs_merged: Math.max(1, Math.round(r.prs_merged * factor)),
    focus_time_pct: Math.min(100, Math.round(r.focus_time_pct * (0.95 + (seed % 10) / 100))),
    ai_loc_share_pct: Math.min(50, Math.round(r.ai_loc_share_pct * (0.9 + (seed % 15) / 100))),
  };
}

// ---------------------------------------------------------------------------
// Caching -- factory-generated scenarios cached per key for session consistency
// ---------------------------------------------------------------------------

type IcScenarioCache = ReturnType<typeof mockIcScenario>;
const icScenarioCache = new Map<string, IcScenarioCache>();
function cachedIcScenario(personId: string): IcScenarioCache {
  let cached = icScenarioCache.get(personId);
  if (!cached) {
    cached = mockIcScenario(personId);
    icScenarioCache.set(personId, cached);
  }
  return cached;
}

/** Returns true when the OData filter describes a previous-period range (end date is in the past). */
function isPrevPeriodFilter(filter: string): boolean {
  const m = /metric_date lt '(\d{4}-\d{2}-\d{2})'/.exec(filter);
  if (!m) return false;
  const endDate = new Date(m[1]);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return endDate <= today;
}

// ---------------------------------------------------------------------------
// IC drill generator -- simple inline drill data per drill type
// ---------------------------------------------------------------------------

function generateDrill(did: string, personId: string): DrillData {
  const seed = filterSeed(`${did}:${personId}`);
  const pid = parseInt(personId.replace('p', ''), 10) || 1;
  const login = `user.${personId}`;

  const date = (total: number, i: number): string =>
    `2026-03-${String(Math.max(1, 31 - Math.round((i * 28) / Math.max(total, 1)))).padStart(2, '0')}`;

  const drillDefs: Record<string, () => DrillData> = {
    'tasks-completed': () => {
      const count = Math.max(3, 5 + Math.round(vary(7, seed, 5)));
      const rows: DrillRow[] = Array.from({ length: count }, (_, i) => ({
        Task: `INSIGHT-${300 + pid * 20 - i * 7}`,
        'Story Points': [1, 2, 3, 5, 3, 2, 1, 5][i % 8] as number,
        'Dev Time': `${Math.max(4, 12 + ([-2, 0, 2, -4, 4, -2, 0, 2][i % 8] as number))}h`,
        Closed: date(count, i),
      }));
      return {
        title: 'Tasks Completed', source: 'Jira', srcClass: 'bg-blue-600',
        value: String(count),
        filter: `assignee = ${login} AND status = Done AND updatedDate >= -30d`,
        columns: ['Task', 'Story Points', 'Dev Time', 'Closed'],
        rows,
      };
    },
    'cycle-time': () => {
      const devTime = Math.max(8, Math.round(vary(14, seed, 6)));
      const count = Math.max(2, Math.round(vary(5, seed, 2)));
      const rows: DrillRow[] = Array.from({ length: count }, (_, i) => ({
        Task: `INSIGHT-${280 + pid * 15 - i * 6}`,
        'Story Points': [3, 2, 5, 1, 3][i % 5] as number,
        'Dev Time': `${devTime + ([-2, 0, 2, -4, 4][i % 5] as number)}h`,
        Status: i === 0 ? 'In Progress' : 'Done',
      }));
      return {
        title: 'Task Development Time', source: 'Jira', srcClass: 'bg-blue-600',
        value: `${devTime}h`,
        filter: `assignee = ${login} AND status changed to "In Progress"`,
        columns: ['Task', 'Story Points', 'Dev Time', 'Status'],
        rows,
      };
    },
    'task-reopen': () => {
      const reopened = seed % 3 === 0 ? 1 : 0;
      return {
        title: 'Reopened Tasks', source: 'Jira', srcClass: 'bg-blue-600',
        value: String(reopened),
        filter: `assignee = ${login} AND status changed from Done to "In Progress" after -14d`,
        columns: ['Task', 'Reason', 'Reopened', 'Resolved'],
        rows: reopened > 0
          ? [{ Task: `INSIGHT-${270 + pid * 5}`, Reason: 'QA regression', Reopened: '2026-03-20', Resolved: '2026-03-21' }]
          : [],
      };
    },
    'commits': () => {
      const count = Math.max(5, Math.round(vary(28, seed, 12)));
      const shown = Math.min(count, 20);
      const rows: DrillRow[] = Array.from({ length: shown }, (_, i) => ({
        Commit: `${personId}${String(i).padStart(3, '0')}x`,
        Repository: ['insight-front', 'insight-api', 'insight-shared'][i % 3] as string,
        '+LOC': Math.round((50 + i * 15) * 1.2),
        '-LOC': Math.round(10 + i * 4),
        Date: date(shown, i),
      }));
      return {
        title: 'Commits', source: 'Bitbucket', srcClass: 'bg-blue-800',
        value: String(count),
        filter: `author = ${login} AND date >= 2026-03-01${count > 20 ? ' (showing last 20)' : ''}`,
        columns: ['Commit', 'Repository', '+LOC', '-LOC', 'Date'],
        rows,
      };
    },
    'pull-requests': () => {
      const count = Math.max(2, Math.round(vary(8, seed, 4)));
      const rows: DrillRow[] = Array.from({ length: count }, (_, i) => ({
        PR: `PR #${500 + pid * 10 - i * 5}`,
        Repository: ['insight-front', 'insight-api', 'insight-shared'][i % 3] as string,
        Status: i === count - 1 && count > 1 ? 'Open' : 'Merged',
        'Cycle Time': i === count - 1 && count > 1 ? '\u2014' : `${Math.max(8, Math.round(vary(16, seed + i, 6)))}h`,
      }));
      return {
        title: 'Pull Requests', source: 'Bitbucket', srcClass: 'bg-blue-800',
        value: String(count),
        filter: `author = ${login} AND created >= 2026-03-01`,
        columns: ['PR', 'Repository', 'Status', 'Cycle Time'],
        rows,
      };
    },
    'reviews': () => {
      const count = Math.max(2, Math.round(vary(10, seed, 5)));
      const reviewers = PEOPLE.map((p) => p.name);
      const rows: DrillRow[] = Array.from({ length: count }, (_, i) => ({
        PR: `PR #${550 + pid * 8 - i * 4}`,
        Author: reviewers[i % reviewers.length] as string,
        Outcome: i % 3 === 1 ? 'Changes Requested' : 'Approved',
        'Time to Review': `${1 + (i % 6)}h`,
      }));
      return {
        title: 'Code Reviews Given', source: 'Bitbucket', srcClass: 'bg-blue-800',
        value: String(count),
        filter: `reviewer = ${login} AND reviewed >= 2026-03-01`,
        columns: ['PR', 'Author', 'Outcome', 'Time to Review'],
        rows,
      };
    },
    'builds': () => {
      const buildPct = Math.min(100, Math.max(70, Math.round(vary(94, seed, 6))));
      return {
        title: 'Build Results', source: 'CI', srcClass: 'bg-gray-600',
        value: `${buildPct}%`,
        filter: `author = ${login} AND build.date >= 2026-03-01`,
        columns: ['Build', 'Branch', 'Status', 'Duration'],
        rows: [
          { Build: `build-${1000 + pid * 10 + 2}`, Branch: 'feat/main-feature', Status: 'Passed',                             Duration: '3m 12s' },
          { Build: `build-${1000 + pid * 10 + 1}`, Branch: 'feat/main-feature', Status: buildPct < 90 ? 'Failed' : 'Passed',   Duration: '2m 08s' },
          { Build: `build-${1000 + pid * 10}`,     Branch: 'fix/bug-fix',       Status: 'Passed',                             Duration: '3m 01s' },
        ],
      };
    },
    'bugs-fixed': () => {
      const count = Math.max(1, Math.round(vary(5, seed, 3)));
      const rows: DrillRow[] = Array.from({ length: count }, (_, i) => ({
        Bug: `INSIGHT-${200 + pid * 15 - i * 8}`,
        Priority: (['High', 'Medium', 'Low', 'Critical', 'Medium', 'High'][i % 6]) as string,
        'Fix Time': `${Math.max(1, Math.round(vary(6, seed + i, 3)))}h`,
        Closed: date(count, i),
      }));
      return {
        title: 'Bugs Fixed', source: 'Jira', srcClass: 'bg-blue-600',
        value: String(count),
        filter: `assignee = ${login} AND issuetype = Bug AND status = Done AND resolved >= 2026-03-01`,
        columns: ['Bug', 'Priority', 'Fix Time', 'Closed'],
        rows,
      };
    },
  };

  const factory = drillDefs[did];
  if (factory) return factory();

  // Fallback for unknown drill IDs
  return {
    title: did, source: 'Unknown', srcClass: 'bg-gray-400',
    value: '0', filter: '', columns: ['Info'], rows: [{ Info: 'No data available' }],
  };
}

// ---------------------------------------------------------------------------
// Factory-generated team members for external consumers
// (replaces the fixture-based TEAM_MEMBERS_MONTH)
// ---------------------------------------------------------------------------

/**
 * All team members (all teams) — derived from registry via factories.
 * Used by components that need the full member list (e.g., sidebar person picker).
 */
export const TEAM_MEMBERS_MONTH: TeamMember[] = mockTeamMemberRows().map((raw) => ({
  person_id: raw.person_id,
  period: 'month' as const,
  name: raw.display_name,
  seniority: raw.seniority,
  tasks_closed: raw.tasks_closed,
  bugs_fixed: raw.bugs_fixed,
  dev_time_h: raw.dev_time_h,
  prs_merged: raw.prs_merged,
  build_success_pct: raw.build_success_pct,
  focus_time_pct: raw.focus_time_pct,
  ai_tools: raw.ai_tools,
  ai_loc_share_pct: raw.ai_loc_share_pct,
}));

// ---------------------------------------------------------------------------
// Mock map -- POST /api/analytics/v1/metrics/{uuid}/query
// ---------------------------------------------------------------------------

/**
 * Each handler receives the OData POST body, infers period / person / team from
 * $filter, and returns the matching mock data wrapped in ODataResponse.
 *
 * POST handlers use factories for raw data generation. The filter string is
 * hashed to produce deterministic variation per period/team/person.
 *
 * Legacy GET entries for dashboard/speed are retained unchanged.
 */
export const insightMockMap = {
  // Legacy screens (not yet migrated to metric queries)
  'GET /api/analytics/v1/dashboard': (): DashboardData => mockDashboardData,
  'GET /api/analytics/v1/speed':     (): SpeedData => mockSpeedData,

  // Executive summary -- returns RawExecSummaryRow[]
  // Teams and headcount come from registry via mockExecRows()
  [`POST /api/analytics/v1/metrics/${METRIC_REGISTRY.EXEC_SUMMARY}/query`]:
    (): ODataResponse<RawExecSummaryRow> => wrap(mockExecRows()),

  // Team members -- returns RawTeamMemberRow[] for the requested team only
  [`POST /api/analytics/v1/metrics/${METRIC_REGISTRY.TEAM_MEMBER}/query`]:
    (body: unknown): ODataResponse<RawTeamMemberRow> => {
      const f = odata(body).$filter ?? '';
      const teamId = team(f);
      const seed = filterSeed(f);
      return wrap(mockTeamMemberRowsForTeam(teamId).map((r, i) => ({ ...r, ...varyMember(r, seed + i) })));
    },

  // Team bullet sections (delivery, quality, collab, AI) -- return RawBulletAggregateRow[]
  ...((['TEAM_BULLET_DELIVERY', 'TEAM_BULLET_QUALITY', 'TEAM_BULLET_COLLAB', 'TEAM_BULLET_AI'] as const).reduce<
    Record<string, (body: unknown) => ODataResponse<RawBulletAggregateRow>>
  >((acc, key) => {
    const sectionMap: Record<typeof key, string> = {
      TEAM_BULLET_DELIVERY: 'task_delivery',
      TEAM_BULLET_QUALITY:  'code_quality',
      TEAM_BULLET_COLLAB:   'collaboration',
      TEAM_BULLET_AI:       'ai_adoption',
    };
    const sectionId = sectionMap[key];
    acc[`POST /api/analytics/v1/metrics/${METRIC_REGISTRY[key]}/query`] =
      (body: unknown): ODataResponse<RawBulletAggregateRow> => {
        const f = odata(body).$filter ?? '';
        const seed = filterSeed(f);
        return wrap(mockTeamBulletSection(sectionId, seed));
      };
    return acc;
  }, {})),

  // IC KPIs -- returns RawIcAggregateRow[]
  // Chooses current vs previous aggregate by inspecting the date range in $filter.
  // A filter whose end date (metric_date lt) is already in the past is a previous-period request.
  //
  // KNOWN MOCK LIMITATION: IC KPI values do not vary across week/month/quarter/year periods.
  // The mock returns the same scenario.kpiAggregate regardless of period granularity.
  // On a real backend, aggregates would differ meaningfully per period.
  // inferPeriodFromODataFilter() is available in periodToDateRange.ts if period-aware variation is added later.
  [`POST /api/analytics/v1/metrics/${METRIC_REGISTRY.IC_KPIS}/query`]:
    (body: unknown): ODataResponse<RawIcAggregateRow> => {
      const f = odata(body).$filter ?? '';
      const pid = person(f);
      const scenario = cachedIcScenario(pid);
      const row = isPrevPeriodFilter(f) ? scenario.prevKpiAggregate : scenario.kpiAggregate;
      return wrap([row]);
    },

  // IC bullet metrics (delivery, collab, AI tools) -- return RawBulletAggregateRow[]
  ...((['IC_BULLET_DELIVERY', 'IC_BULLET_COLLAB', 'IC_BULLET_AI'] as const).reduce<
    Record<string, (body: unknown) => ODataResponse<RawBulletAggregateRow>>
  >((acc, key) => {
    const sectionMap: Record<typeof key, readonly string[]> = {
      IC_BULLET_DELIVERY: ['task_delivery', 'git_output', 'code_quality'],
      IC_BULLET_COLLAB:   ['collab'],
      IC_BULLET_AI:       ['ai_tools'],
    };
    const sectionIds = sectionMap[key];
    // KNOWN MOCK LIMITATION: IC bullet metrics ignore the period filter entirely.
    // All periods (week/month/quarter/year) return identical scenario.bullets data.
    acc[`POST /api/analytics/v1/metrics/${METRIC_REGISTRY[key]}/query`] =
      (body: unknown): ODataResponse<RawBulletAggregateRow> => {
        const f = odata(body).$filter ?? '';
        const pid = person(f);
        const scenario = cachedIcScenario(pid);
        const items = sectionIds.flatMap((section) => scenario.bullets[section] ?? []);
        return wrap(items);
      };
    return acc;
  }, {})),

  // IC chart: LOC trend -- returns RawLocTrendRow[]
  // KNOWN MOCK LIMITATION: chart data points are identical across periods.
  // Only the x-axis labels reformat (Mon/Tue for week, W1/W2 for month, etc.) via transforms.ts formatDateLabel().
  [`POST /api/analytics/v1/metrics/${METRIC_REGISTRY.IC_CHART_LOC}/query`]:
    (body: unknown): ODataResponse<RawLocTrendRow> => {
      const f = odata(body).$filter ?? '';
      const pid = person(f);
      const scenario = cachedIcScenario(pid);
      return wrap(scenario.locTrend);
    },

  // IC chart: delivery trend -- returns RawDeliveryTrendRow[]
  [`POST /api/analytics/v1/metrics/${METRIC_REGISTRY.IC_CHART_DELIVERY}/query`]:
    (body: unknown): ODataResponse<RawDeliveryTrendRow> => {
      const f = odata(body).$filter ?? '';
      const pid = person(f);
      const scenario = cachedIcScenario(pid);
      return wrap(scenario.deliveryTrend);
    },

  // IC drills -- drill_id extracted from $filter; person also from $filter
  [`POST /api/analytics/v1/metrics/${METRIC_REGISTRY.IC_DRILL}/query`]:
    (body: unknown): ODataResponse<DrillData> => {
      const f   = odata(body).$filter ?? '';
      const did = drillId(f);
      const pid = person(f);
      if (!did) return wrap([]);
      return wrap([generateDrill(did, pid)]);
    },

  // IC time-off notices -- returns empty by default (no time off scheduled)
  [`POST /api/analytics/v1/metrics/${METRIC_REGISTRY.IC_TIMEOFF}/query`]:
    (_body: unknown): ODataResponse<TimeOffNotice> => wrap([]),
} satisfies MockMap;
